"""Adiciona campo departamento à tabela historico_status

Revision ID: a1f8b2c3d4e5
Revises: 1fc90ce64182
Create Date: 2026-06-02 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f8b2c3d4e5'
down_revision = '1fc90ce64182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_status', sa.Column('departamento', sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historico_status', 'departamento')
    # ### end Alembic commands ###
