"""Adiciona campo pesquisa_id à tabela cotacoes para rastrear origem de pesquisa

Revision ID: b9f3c2d5e1a6
Revises: a1f8b2c3d4e5
Create Date: 2026-06-10 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f3c2d5e1a6'
down_revision = 'a1f8b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotacoes', sa.Column('pesquisa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cotacoes', 'pesquisas_mercado', ['pesquisa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotacoes', type_='foreignkey')
    op.drop_column('cotacoes', 'pesquisa_id')
    # ### end Alembic commands ###
